name: CI
on: [push]

jobs:
  cargo_test:
    name: Test (Linux x86-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            compiler/target
            rt/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test compiler
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path compiler/Cargo.toml
      - name: Test runtime
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rt/Cargo.toml
